# Server configuration
server:
  port: 8081
  servlet:
    context-path: /dm
    session.timeout: 30s

# Components configuration
system.element:
  dm:
    host: localhost
    port: 8082
  queue:
    host:
    port:
