# Server configuration
server:
  port: 8081
  servlet:
    context-path: /dm
    session.timeout: 30s
  error:
    include-message: always

spring:
  jackson:
    default-property-inclusion: non_null

# Components configuration
system.element:
  dm:
    host: localhost
    port: 8082
  queue:
    host: "[::1]"
    port: 9092

logging.level:
  org.apache.ignite:
        internal: WARN
